#+TITLE: Extending Containers on LUMI
#+AUTHOR: Shanshan Wang
#+OPTIONS: toc:nil
#+OPTIONS: num:t

* Introduction
In this documentation, we provide examples of how to extend a prebuilt container and install system packages such as Poppler (a PDF rendering library) and Python packages.

* Extending Containers Built by LUMI
The current LUMI AI Factory multi-framework container is available at =/appl/local/laifs/containers/lumi-multitorch-latest.sif=. In this guide, we use it as the base image.

** Allocate resources
Building containers requires memory, so it is recommended to allocate resources before extending the container:

#+BEGIN_SRC bash
srun --account=<project> --partition=dev-g --ntasks=1 --cpus-per-task=7 --gpus-per-node=1 --mem=120G --time=02:30:00 --nodes=1 --pty bash
#+END_SRC

** Copy the container to your scratch folder
It is always recommended to copy the container you plan to extend to your scratch folder, as the original container may be updated or deleted:

#+BEGIN_SRC bash
cp /appl/local/laifs/containers/lumi-multitorch-latest.sif /scratch/<project>/<user>/lumi-multitorch-base.sif
#+END_SRC

** Load necessary modules
#+BEGIN_SRC bash
module purge
module load CrayEnv
module load PRoot
#+END_SRC

** Create a definition file
Create a definition file (e.g., =poppler-lumi.def=) where you define the packages to be installed:

#+BEGIN_SRC bash
Bootstrap: localimage
From: /scratch/<project>/<user>/lumi-multitorch-base.sif

%post
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y poppler-utils
    apt-get clean
    rm -rf /var/lib/apt/lists/*
#+END_SRC

** Build the container
Use Singularity to build the new container:

#+BEGIN_SRC bash
singularity build /scratch/<project>/<user>/lumi-poppler.sif poppler-lumi.def
#+END_SRC

** Notes
Building containers can take time, so you may not want to rebuild each time you need a new package.

*** Python packages
For new Python packages, create a virtual environment after loading the container:

#+BEGIN_SRC bash
export SIF=/scratch/<project>/<user>/lumi-poppler.sif
singularity shell $SIF
Singularity> python -m venv h5-env --system-site-packages
Singularity> source h5-env/bin/activate
(h5-env) Singularity> pip install pdf2image h5py
#+END_SRC

*** System packages
For new system packages, it is good to rebuild the container.
*** To check installed system and Python packages in the existing container:

#+BEGIN_SRC bash
export SIF=/scratch/<project>/<user>/lumi-multitorch-base.sif
singularity shell $SIF
Singularity> dpkg -l
Singularity> pip list
#+END_SRC

*** Overall workflow
#+BEGIN_SRC bash
srun --account=<project> --partition=dev-g --ntasks=1 --cpus-per-task=7 --gpus-per-node=1 --mem=60G --time=02:30:00 --nodes=1 --pty bash
export SIF=/scratch/<project>/<user>/lumi-poppler.sif
module use /appl/local/laifs/modules
module load lumi-aif-singularity-bindings
srun singularity exec $SIF bash -c 'source h5-env/bin/activate && python my-script.py'
#+END_SRC

* Extending Containers Built by CSC
Containers maintained by CSC are based on Ubuntu. CSC prebuilt PyTorch containers are located in =/appl/local/csc/soft/ai/images=. In this guide, we use =pytorch_2.7.1_lumi.sif= as an example.

** Allocate resources
#+BEGIN_SRC bash
srun --account=<project> --partition=dev-g --ntasks=1 --cpus-per-task=7 --gpus-per-node=1 --mem=120G --time=02:30:00 --nodes=1 --pty bash
#+END_SRC

** Copy the container to your scratch folder
#+BEGIN_SRC bash
cp /appl/local/csc/soft/ai/images/pytorch_2.7.1_lumi.sif /scratch/<project>/<user>
#+END_SRC

** Load necessary modules
#+BEGIN_SRC bash
module purge
module load CrayEnv
module load PRoot
#+END_SRC

** Create a definition file
Create a definition file (e.g., =poppler-csc.def=) where you define the packages to be installed:

#+BEGIN_SRC bash
Bootstrap: localimage
From: pytorch_2.7.1_lumi.sif

%post
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y poppler-utils && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
#+END_SRC

** Build the container
#+BEGIN_SRC bash
singularity build /scratch/<project>/<user>/csc-poppler.sif poppler-csc.def
#+END_SRC

** Notes
Building containers can take time, so avoid rebuilding each time a new package is needed.

*** Python packages
For new Python packages, create a virtual environment after loading the container:

#+BEGIN_SRC bash
module use /appl/local/csc/modulefiles/
module load pytorch/2.7
export SING_IMAGE='/scratch/<project>/<user>/csc-poppler.sif'
python -m venv h5-env --system-site-packages
source h5-env/bin/activate
pip install h5py
#+END_SRC

*** System packages
For new system packages, it is good to rebuild the container.
*** To check installed system and Python packages:

#+BEGIN_SRC bash
module use /appl/local/csc/modulefiles/
module load pytorch/2.7
module show pytorch   # Lists the location of the container
singularity_wrapper shell
dpkg -l
pip list
#+END_SRC

*** Overall workflow
#+BEGIN_SRC bash
srun --account=<project> --partition=dev-g --ntasks=1 --cpus-per-task=7 --gpus-per-node=1 --mem=60G --time=02:30:00 --nodes=1 --pty bash
module use /appl/local/csc/modulefiles/
module load pytorch/2.7
export SING_IMAGE='/scratch/<project>/<user>/csc-poppler.sif'
source h5-env/bin/activate
python my-script.py
#+END_SRC
* Extending Pytorch Containers on Mahti
#+BEGIN_SRC bash
module use /appl/local/csc/modulefiles/
module load pytorch/2.7
module show pytorch   # Lists the location of the container
#+END_SRC

It shows the path of the pytorch container as ="SING_IMAGE","/appl/soft/ai/wrap/pytorch-2.7/container.sif")=, copy the container to your scratch folder =cp /appl/soft/ai/wrap/pytorch-2.7/container.sif /scratch/project_id/username=. Check which system this container is built upon, =apptainer exec container.sif cat /etc/os-release=. On mahti, the container is built on the Rocky-linux, so in the def file =poppler-csc.def= where we need to install poppler-utils, we define as follows:

#+BEGIN_SRC bash
Bootstrap: localimage
From: container.sif

%post
    dnf -y install poppler-utils && \
    dnf -y clean all
#+END_SRC

Next, build the new container which includes poppler-utils,


#+BEGIN_SRC bash
  export APPTAINER_TMPDIR=$TMPDIR
  export APPTAINER_CACHEDIR=$TMPDIR/apptainer-cache
  apptainer build --fakeroot csc-poppler.sif poppler-csc.def
#+END_SRC

After building, one can go inside the new container by =apptainer shell csc-poppler.sif=, and one can create a python virtual environment inside the new container
#+BEGIN_SRC bash
  python -m venv h5-env --system-site-packages
  source h5-env/bin/activate
  pip install pdf2image h5py
#+END_SRC

Test if the poppler works,
#+BEGIN_SRC python
  from pdf2image import convert_from_path
  images = convert_from_path('sample.pdf', fmt='png')
#+END_SRC

* References
- [[https://github.com/Lumi-supercomputer/LUMI-AI-Guide/tree/main/2-setting-up-environment]]
- [[https://lumi-supercomputer.github.io/LUMI-training-materials/2day-20240502/09_Containers/]]
